export enum SupportedCoins {
  BTCUSDT = "BTCUSDT",
  ETHUSDT = "ETHUSDT",
  SOLUSDT = "SOLUSDT",
  BNBUSDT = "BNBUSDT",
  XRPUSDT = "XRPUSDT",
  ADAUSDT = "ADAUSDT",
  DOTUSDT = "DOTUSDT",
  DOGEUSDT = "DOGEUSDT",
  AVAXUSDT = "AVAXUSDT",
  MATICUSDT = "MATICUSDT",
}
